### ISSUE TITLE
mismatch between expected and downloaded content

### ISSUE THREAD

**Issue by cramjaco** [conda-forge/r-ape-feedstock#4]
When I try to download ape through conda forge the downloaded file's md5sum doesn't match its expected md5sum and the installation fails, here is an example:

` conda create -n apeissue2 -c conda-forge r r-ape`

The installation concludes with three repetitions of the following error:

```

> CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
> for url 'https://conda.anaconda.org/conda-forge/linux-64/r-ape-5.1-r3.4.1_0.tar.bz2'.
>   download saved to: /home/cramjaco/Programs/anaconda3/pkgs/r-ape-5.1-r3.4.1_0.tar.bz2
>   expected md5 sum: 6dbaebd6b99f057d96691b282e419eb6
>   actual md5 sum: c7491770191ec0648dcde4d299b74092
> 

```

Happy to provide more information as needed. For what its worth, here is my output of conda info

Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.8.0
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/cramjaco/Programs/anaconda3  (writable)
    default environment : /home/cramjaco/Programs/anaconda3
       envs directories : /home/cramjaco/Programs/anaconda3/envs
                          /home/cramjaco/.conda/envs
          package cache : /home/cramjaco/Programs/anaconda3/pkgs
                          /home/cramjaco/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/cramjaco/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.12.4 CPython/3.6.0 Linux/3.13.0-143-generic debian/jessie/sid glibc/2.19
                UID:GID : 56914:56914

**Comment by jdblischak** [comment]
@cramjaco Thanks for the report!

I confirmed that I obtain the same error with a similar setup (conda 4.3.34, Ubuntu 17.10). According to the discussion in https://github.com/conda/conda/issues/6121, this is likely a transient issue with the server. r-ape was recently updated to 5.1 via PR #3, so I'm guessing the servers haven't synced yet.

For a short-term solution, you can install the 5.0 version of r-ape:

```
conda create -n apeissue2 -c conda-forge r r-ape=5.0
```

**Comment by johnmous** [comment]
4 days later the issue persists. In https://anaconda.org/conda-forge/r-ape/files I see two files named  | r-ape-5.1-r3.4.1_0.tar.bz2 one with the erroneous md5 adn one with the correct. Can someone fix it?

**Comment by jdblischak** [comment]
> I see two files named | r-ape-5.1-r3.4.1_0.tar.bz2 one with the erroneous md5 adn one with the correct.

@johnmous Good observation! Something clearly went wrong here. It appears that the correct version of  linux-64/r-ape-5.1-r3.4.1_0.tar.bz2 (md5: 6dbaebd...) was uploaded to Anaconda Cloud, but then subsequently a broken version (md5: c749177...) was also uploaded.

@conda-forge/core Could someone please mark the corrupt package as broken? It's the linux-64/r-ape-5.1-r3.4.1_0.tar.bz2  with downloads.

**Comment by djsutherland** [comment]
@jdblischak Done; sorry for the delay.

It looks like two builds were kicked off for some reason: [43](https://circleci.com/gh/conda-forge/r-ape-feedstock/43) and [46](https://circleci.com/gh/conda-forge/r-ape-feedstock/46) for R 3.4.1, and [44](https://circleci.com/gh/conda-forge/r-ape-feedstock/44) / [45](https://circleci.com/gh/conda-forge/r-ape-feedstock/45) for 3.3.2. No errors in any of the logs, but only one 3.3.2 build got uploaded and both 3.4.2 did....

**Comment by jdblischak** [comment]
Thanks @dougalsutherland! I confirmed that I could download r-ape 5.1 on linux-64.
